### ISSUE TITLE
nginx when and better html lol now i am just complaining.

### ISSUE THREAD

**Issue by ohlookitsAugust** [iamhansen/bean#8]
title says everything.

**Comment by iamhansen** [comment]
angery
express is bae :heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart::heart:

**Comment by iamhansen** [comment]
also you barely develop so try working on that lol lmao xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
